add_newline = false
command_timeout = 1000
#format = """($git_branch$git_status\n)$username$kubernetes$directory"""
format = """$username($git_branch) $kubernetes$directory"""
#right_format="""$git_branch$git_status""""
#right_format="""$character"""

# Drop ugly default prompt characters
[character]
success_symbol = ''
error_symbol = ''
#success_symbol = "[](fg:#262627)[](bg:#262627 fg:#3b3b3d)[ 󰄬 ](bold bg:#3b3b3d fg:green)"
#error_symbol = "[](fg:#262627)[](bq:#262627 fq:#3b3b3d)[ × ](bold bq:#3b3b3d fq:red)"
#format = '$symbol' # the default format contains a space after the $symbol variable


# Shows the username
[username]
style_user = 'green'
style_root = 'black bold'
format = '[$user]($style)[@](bold red) '
disabled = false
show_always = true

# Shows current directory
[directory]
truncation_length = 1
truncation_symbol = '…/'
home_symbol = '~'
read_only_style = '197'
read_only = '  '
format = '[$path](bold purple)[$read_only]($read_only_style) [λ](blue)'

# Shows current git branch
[git_branch]
symbol = ' '
format = '\[[$symbol$branch]($style)\]'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold blue'

# Shows current git status
[git_status]
format = '([ \($all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[ confliced=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = '[ ahead=${count}](bold blue)'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple)'
disabled = false

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true

