// MARK: - Desktop Groups

const youPageDesktopGroups_Sections = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الصورة الرمزية الخاصة بك",
            "ca": "Amaga el teu avatar",
            "zh-CN": "隐藏你的头像",
            "zh-TW": "隱藏你的頭像",
            "hr": "Sakrij svoj avatar",
            "cs": "Skryjte svého avatara",
            "da": "Skjul din avatar",
            "nl": "Verberg je avatar",
            "en": "Hide Your Avatar",
            "fi": "Piilota avatarisi",
            "fr": "Cachez votre avatar",
            "de": "Verstecke deinen Avatar",
            "el": "Απόκρυψη του Avatar σας",
            "he": "הסתר את הדמות שלך",
            "hi": "अपना अवतार छुपाएं",
            "hu": "Rejtsd el az Avatarod",
            "id": "Sembunyikan Avatar Anda",
            "it": "Nascondi il tuo avatar",
            "ja": "アバターを隠す",
            "ko": "아바타 숨기기",
            "ms": "Sembunyikan Avatar Anda",
            "nb": "Skjul avataren din",
            "pl": "Ukryj swój awatar",
            "pt": "Esconda seu avatar",
            "ro": "Ascunde-ți avatarul",
            "ru": "Скрыть свой аватар",
            "sk": "Skryte svojho avatara",
            "es": "Oculta tu avatar",
            "sv": "Göm din avatar",
            "th": "ซ่อนอวตารของคุณ",
            "tr": "Avatarınızı Gizleyin",
            "uk": "Приховати свій аватар",
            "vi": "Ẩn hình đại diện của bạn"
          },
        id: "untrap_you_page_hide_your_avatar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'التاريخ'",
            "ca": "Amaga la secció 'Historial'",
            "zh-CN": "隐藏“历史”部分",
            "zh-TW": "隱藏「歷史」部分",
            "hr": "Sakrij odjeljak 'Povijest'",
            "cs": "Skrýt sekci 'Historie'",
            "da": "Skjul afsnittet 'Historie'",
            "nl": "Sectie 'Geschiedenis' verbergen",
            "en": "Hide 'History' Section",
            "fi": "Piilota 'Historia'-osio",
            "fr": "Masquer la section « Historique »",
            "de": "Abschnitt „Verlauf“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Ιστορικό'",
            "he": "הסתר קטע 'היסטוריה'",
            "hi": "'इतिहास' अनुभाग छिपाएँ",
            "hu": "Az „Előzmények” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Riwayat'",
            "it": "Nascondi la sezione 'Cronologia'",
            "ja": "「履歴」セクションを非表示にする",
            "ko": "'기록' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Sejarah'",
            "nb": "Skjul 'Historikk'-delen",
            "pl": "Ukryj sekcję „Historia”",
            "pt": "Ocultar a seção 'Histórico'",
            "ro": "Ascundeți secțiunea „Istoric”",
            "ru": "Скрыть раздел «История»",
            "sk": "Skryť sekciu História",
            "es": "Ocultar la sección 'Historial'",
            "sv": "Dölj avsnittet 'Historik'",
            "th": "ซ่อนส่วน 'ประวัติ'",
            "tr": "'Geçmiş' Bölümünü Gizle",
            "uk": "Сховати розділ «Історія»",
            "vi": "Ẩn phần 'Lịch sử'"
          },
        id: "untrap_you_page_hide_section_history",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'المشاهدة لاحقًا'",
            "ca": "Amaga la secció 'Mira més tard'",
            "zh-CN": "隐藏“稍后观看”部分",
            "zh-TW": "隱藏“稍後觀看”部分",
            "hr": "Sakrij odjeljak 'Gledaj kasnije'",
            "cs": "Skrýt sekci Přehrát později",
            "da": "Skjul afsnittet 'Se senere'",
            "nl": "Sectie 'Later bekijken' verbergen",
            "en": "Hide 'Watch Later' Section",
            "fi": "Piilota Katso myöhemmin -osio",
            "fr": "Masquer la section « Regarder plus tard »",
            "de": "Abschnitt „Später ansehen“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Παρακολούθηση αργότερα'",
            "he": "הסתר את הקטע 'צפה מאוחר יותר'",
            "hi": "'बाद में देखें' अनुभाग छिपाएँ",
            "hu": "A „Megnézendő videók” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Tonton Nanti'",
            "it": "Nascondi la sezione 'Guarda più tardi'",
            "ja": "「後で見る」セクションを非表示にする",
            "ko": "'나중에 보기' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Tonton Kemudian'",
            "nb": "Skjul 'Se senere'-delen",
            "pl": "Ukryj sekcję „Do obejrzenia”",
            "pt": "Ocultar a seção 'Assistir mais tarde'",
            "ro": "Ascundeți secțiunea „Vizionați mai târziu”",
            "ru": "Скрыть раздел «Посмотреть позже»",
            "sk": "Skryť sekciu Pozrieť neskôr",
            "es": "Ocultar la sección 'Ver más tarde'",
            "sv": "Dölj avsnittet 'Titta senare'",
            "th": "ซ่อนส่วน 'ดูภายหลัง'",
            "tr": "'Daha Sonra İzle' Bölümünü Gizle",
            "uk": "Сховати розділ «Переглянути пізніше»",
            "vi": "Ẩn phần 'Xem sau'"
          },
        id: "untrap_you_page_hide_section_watch_later",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'قوائم التشغيل'",
            "ca": "Amaga la secció 'Llistes de reproducció'",
            "zh-CN": "隐藏“播放列表”部分",
            "zh-TW": "隱藏“播放清單”部分",
            "hr": "Sakrij odjeljak 'Popisi za reprodukciju'",
            "cs": "Skrýt sekci „Seznamy skladeb“",
            "da": "Skjul sektionen 'Playlister'",
            "nl": "Sectie 'Afspeellijsten' verbergen",
            "en": "Hide 'Playlists' Section",
            "fi": "Piilota Soittolistat-osio",
            "fr": "Masquer la section « Playlists »",
            "de": "Abschnitt „Playlists“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Λίστες αναπαραγωγής'",
            "he": "הסתר את הקטע 'פלייליסטים'",
            "hi": "'प्लेलिस्ट' अनुभाग छिपाएँ",
            "hu": "A „Lejátszási listák” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Daftar Putar'",
            "it": "Nascondi la sezione 'Playlist'",
            "ja": "「プレイリスト」セクションを非表示にする",
            "ko": "'재생 목록' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Senarai Main'",
            "nb": "Skjul delen 'Spillelister'",
            "pl": "Ukryj sekcję „Playlisty”",
            "pt": "Ocultar a seção 'Playlists'",
            "ro": "Ascundeți secțiunea „Playlisturi”",
            "ru": "Скрыть раздел «Плейлисты»",
            "sk": "Skryť sekciu Zoznamy skladieb",
            "es": "Ocultar la sección 'Listas de reproducción'",
            "sv": "Dölj avsnittet 'Spellistor'",
            "th": "ซ่อนส่วน 'เพลย์ลิสต์'",
            "tr": "'Oynatma Listeleri' Bölümünü Gizle",
            "uk": "Сховати розділ «Списки відтворення»",
            "vi": "Ẩn phần 'Danh sách phát'"
          },
        id: "untrap_you_page_hide_section_playlists",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'مقاطع الفيديو التي أعجبتني'",
            "ca": "Amaga la secció 'Vídeos que m'agraden'",
            "zh-CN": "隐藏“喜欢的视频”部分",
            "zh-TW": "隱藏「喜歡的影片」部分",
            "hr": "Sakrij odjeljak 'Sviđa mi se'",
            "cs": "Skrýt sekci „Oblíbená videa“",
            "da": "Skjul afsnittet 'Likede videoer'",
            "nl": "Verberg het gedeelte 'Gelikete video's'",
            "en": "Hide 'Liked Videos' Section",
            "fi": "Piilota 'Pidätyt videot' -osio",
            "fr": "Masquer la section « Vidéos aimées »",
            "de": "Abschnitt „Gefällt mir Videos“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Βίντεο που αρέσουν'",
            "he": "הסתר את הקטע 'סרטונים שאהבתי'",
            "hi": "'पसंद किए गए वीडियो' अनुभाग छुपाएं",
            "hu": "A „Kedvelt videók” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Video yang Disukai'",
            "it": "Nascondi la sezione 'Video piaciuti'",
            "ja": "「いいね！」セクションを非表示にする",
            "ko": "'좋아요 표시한 동영상' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Video Suka'",
            "nb": "Skjul delen 'Likte videoer'",
            "pl": "Ukryj sekcję „Polubione filmy”",
            "pt": "Ocultar a seção 'Vídeos curtidos'",
            "ro": "Ascundeți secțiunea „Videoclipuri apreciate”",
            "ru": "Скрыть раздел «Понравившиеся видео»",
            "sk": "Skryť sekciu „Páči sa mi videá“",
            "es": "Ocultar la sección 'Videos que me gustan'",
            "sv": "Dölj avsnittet 'Gillade videor'",
            "th": "ซ่อนส่วน 'วิดีโอที่ชอบ'",
            "tr": "'Beğenilen Videolar' Bölümünü Gizle",
            "uk": "Сховати розділ «Сподобалися відео»",
            "vi": "Ẩn phần 'Video đã thích'"
          },
        id: "untrap_you_page_hide_section_liked_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'مقاطعك'",
            "ca": "Amaga la secció 'Els teus clips'",
            "zh-CN": "隐藏“您的剪辑”部分",
            "zh-TW": "隱藏“您的剪輯”部分",
            "hr": "Sakrij odjeljak 'Vaši isječci'",
            "cs": "Skrýt sekci „Vaše klipy“",
            "da": "Skjul afsnittet 'Dine klip'",
            "nl": "Verberg het gedeelte 'Uw clips'",
            "en": "Hide 'Your Clips' Section",
            "fi": "Piilota 'Omat leikkeet' -osio",
            "fr": "Masquer la section « Vos clips »",
            "de": "Bereich „Deine Clips“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Τα κλιπ σας'",
            "he": "הסתר את הקטע 'הקליפים שלך'",
            "hi": "'आपकी क्लिप्स' अनुभाग छिपाएँ",
            "hu": "A 'Saját klipek' szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Klip Anda'",
            "it": "Nascondi la sezione 'I tuoi clip'",
            "ja": "「あなたのクリップ」セクションを非表示にする",
            "ko": "'내 클립' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Klip Anda'",
            "nb": "Skjul delen 'Dine klipp'",
            "pl": "Ukryj sekcję „Twoje klipy”",
            "pt": "Ocultar a seção 'Seus clipes'",
            "ro": "Ascundeți secțiunea „Clipurile dvs.”",
            "ru": "Скрыть раздел «Ваши клипы»",
            "sk": "Skryť sekciu „Vaše klipy“",
            "es": "Ocultar la sección 'Tus clips'",
            "sv": "Dölj avsnittet 'Dina klipp'",
            "th": "ซ่อนส่วน 'คลิปของคุณ'",
            "tr": "'Klipleriniz' Bölümünü Gizle",
            "uk": "Сховати розділ «Ваші кліпи»",
            "vi": "Ẩn phần 'Clip của bạn'"
          },
        id: "untrap_you_page_hide_section_your_clips",
        defaultValue: false
    }
];

// MARK: - Mobile Groups

const youPageMobileGroups_Sections = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'التاريخ'",
            "ca": "Amaga la secció 'Historial'",
            "zh-CN": "隐藏“历史”部分",
            "zh-TW": "隱藏「歷史」部分",
            "hr": "Sakrij odjeljak 'Povijest'",
            "cs": "Skrýt sekci 'Historie'",
            "da": "Skjul afsnittet 'Historie'",
            "nl": "Sectie 'Geschiedenis' verbergen",
            "en": "Hide 'History' Section",
            "fi": "Piilota 'Historia'-osio",
            "fr": "Masquer la section « Historique »",
            "de": "Abschnitt „Verlauf“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Ιστορικό'",
            "he": "הסתר קטע 'היסטוריה'",
            "hi": "'इतिहास' अनुभाग छिपाएँ",
            "hu": "Az „Előzmények” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Riwayat'",
            "it": "Nascondi la sezione 'Cronologia'",
            "ja": "「履歴」セクションを非表示にする",
            "ko": "'기록' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Sejarah'",
            "nb": "Skjul 'Historikk'-delen",
            "pl": "Ukryj sekcję „Historia”",
            "pt": "Ocultar a seção 'Histórico'",
            "ro": "Ascundeți secțiunea „Istoric”",
            "ru": "Скрыть раздел «История»",
            "sk": "Skryť sekciu História",
            "es": "Ocultar la sección 'Historial'",
            "sv": "Dölj avsnittet 'Historik'",
            "th": "ซ่อนส่วน 'ประวัติ'",
            "tr": "'Geçmiş' Bölümünü Gizle",
            "uk": "Сховати розділ «Історія»",
            "vi": "Ẩn phần 'Lịch sử'"
          },
        id: "untrap_you_page_hide_section_history",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'قوائم التشغيل'",
            "ca": "Amaga la secció 'Llistes de reproducció'",
            "zh-CN": "隐藏“播放列表”部分",
            "zh-TW": "隱藏“播放清單”部分",
            "hr": "Sakrij odjeljak 'Popisi za reprodukciju'",
            "cs": "Skrýt sekci „Seznamy skladeb“",
            "da": "Skjul sektionen 'Playlister'",
            "nl": "Sectie 'Afspeellijsten' verbergen",
            "en": "Hide 'Playlists' Section",
            "fi": "Piilota Soittolistat-osio",
            "fr": "Masquer la section « Playlists »",
            "de": "Abschnitt „Playlists“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Λίστες αναπαραγωγής'",
            "he": "הסתר את הקטע 'פלייליסטים'",
            "hi": "'प्लेलिस्ट' अनुभाग छिपाएँ",
            "hu": "A „Lejátszási listák” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Daftar Putar'",
            "it": "Nascondi la sezione 'Playlist'",
            "ja": "「プレイリスト」セクションを非表示にする",
            "ko": "'재생 목록' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Senarai Main'",
            "nb": "Skjul delen 'Spillelister'",
            "pl": "Ukryj sekcję „Playlisty”",
            "pt": "Ocultar a seção 'Playlists'",
            "ro": "Ascundeți secțiunea „Playlisturi”",
            "ru": "Скрыть раздел «Плейлисты»",
            "sk": "Skryť sekciu Zoznamy skladieb",
            "es": "Ocultar la sección 'Listas de reproducción'",
            "sv": "Dölj avsnittet 'Spellistor'",
            "th": "ซ่อนส่วน 'เพลย์ลิสต์'",
            "tr": "'Oynatma Listeleri' Bölümünü Gizle",
            "uk": "Сховати розділ «Списки відтворення»",
            "vi": "Ẩn phần 'Danh sách phát'"
          },
        id: "untrap_you_page_hide_section_playlists",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'مقاطع الفيديو الخاصة بك'",
            "ca": "Amaga la secció 'Els teus vídeos'",
            "zh-CN": "隐藏“您的视频”部分",
            "zh-TW": "隱藏“您的影片”部分",
            "hr": "Sakrij odjeljak 'Vaši videozapisi'",
            "cs": "Skryjte sekci „Vaše videa“",
            "da": "Skjul sektionen 'Dine videoer'",
            "nl": "Verberg het gedeelte 'Je video's'",
            "en": "Hide 'Your Videos' Section",
            "fi": "Piilota 'Omat videot' -osio",
            "fr": "Masquer la section « Vos vidéos »",
            "de": "Blenden Sie den Abschnitt „Ihre Videos“ aus",
            "el": "Απόκρυψη ενότητας 'Τα βίντεό σας'",
            "he": "הסתר את הקטע 'הסרטונים שלך'",
            "hi": "'आपके वीडियो' अनुभाग छिपाएँ",
            "hu": "A 'Saját videóid' szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Video Anda'",
            "it": "Nascondi la sezione 'I tuoi video'",
            "ja": "「あなたのビデオ」セクションを非表示にする",
            "ko": "'내 동영상' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Video Anda'",
            "nb": "Skjul delen 'Dine videoer'",
            "pl": "Ukryj sekcję „Twoje filmy”",
            "pt": "Ocultar a seção 'Seus vídeos'",
            "ro": "Ascundeți secțiunea „Videoclipurile tale”",
            "ru": "Скрыть раздел «Ваши видео»",
            "sk": "Skryť sekciu „Vaše videá“",
            "es": "Ocultar la sección 'Tus vídeos'",
            "sv": "Dölj avsnittet 'Dina videor'",
            "th": "ซ่อนส่วน 'วิดีโอของคุณ'",
            "tr": "'Videolarınız' Bölümünü Gizle",
            "uk": "Сховати розділ «Ваші відео»",
            "vi": "Ẩn phần 'Video của bạn'"
          },
        id: "untrap_you_page_hide_section_your_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'أفلامك'",
            "ca": "Amaga la secció 'Les teves pel·lícules'",
            "zh-CN": "隐藏“您的电影”部分",
            "zh-TW": "隱藏“您的電影”部分",
            "hr": "Sakrij odjeljak 'Vaši filmovi'",
            "cs": "Skrýt sekci „Vaše filmy“",
            "da": "Skjul sektionen 'Dine film'",
            "nl": "Verberg het gedeelte 'Uw films'",
            "en": "Hide 'Your Movies' Section",
            "fi": "Piilota 'Omat elokuvat' -osio",
            "fr": "Masquer la section « Vos films »",
            "de": "Blenden Sie den Abschnitt „Ihre Filme“ aus",
            "el": "Απόκρυψη ενότητας 'Οι ταινίες σας'",
            "he": "הסתר את הקטע 'הסרטים שלך'",
            "hi": "'आपकी फिल्में' अनुभाग छुपाएं",
            "hu": "A „Saját filmek” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Film Anda'",
            "it": "Nascondi la sezione 'I tuoi film'",
            "ja": "「あなたの映画」セクションを非表示にする",
            "ko": "'내 영화' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Filem Anda'",
            "nb": "Skjul delen 'Dine filmer'",
            "pl": "Ukryj sekcję „Twoje filmy”",
            "pt": "Ocultar a seção 'Seus filmes'",
            "ro": "Ascundeți secțiunea „Filmele dvs.”",
            "ru": "Скрыть раздел «Ваши фильмы»",
            "sk": "Skryť sekciu „Vaše filmy“",
            "es": "Ocultar la sección 'Tus películas'",
            "sv": "Dölj avsnittet 'Dina filmer'",
            "th": "ซ่อนส่วน 'ภาพยนตร์ของคุณ'",
            "tr": "'Filmleriniz' Bölümünü Gizle",
            "uk": "Сховати розділ «Ваші фільми»",
            "vi": "Ẩn phần 'Phim của bạn'"
          },
        id: "untrap_you_page_hide_section_your_movies",
        defaultValue: false
    }
];

// MARK: - Builder

// Desktop

const youPageDesktopGroups = [
    {
        groupName: {
            "ar": "الأقسام",
            "ca": "Seccions",
            "zh-CN": "部分",
            "zh-TW": "部分",
            "hr": "Sekcije",
            "cs": "Sekce",
            "da": "Afsnit",
            "nl": "Secties",
            "en": "Sections",
            "fi": "Osat",
            "fr": "Sections",
            "de": "Abschnitte",
            "el": "Ενότητες",
            "he": "מקטעים",
            "hi": "धारा",
            "hu": "Szakaszok",
            "id": "Bagian",
            "it": "Sezioni",
            "ja": "セクション",
            "ko": "섹션",
            "ms": "Bahagian",
            "nb": "Seksjoner",
            "pl": "Sekcje",
            "pt": "Seções",
            "ro": "Secțiuni",
            "ru": "Разделы",
            "sk": "Sekcie",
            "es": "Secciones",
            "sv": "Avsnitt",
            "th": "ส่วนต่างๆ",
            "tr": "Bölümler",
            "uk": "Розділи",
            "vi": "Phần"
          },
        groupId: "sections",
        parentCategoryId: "youPage",
        options: youPageDesktopGroups_Sections
    }
];

// Mobile

const youPageMobileGroups = [
    {
        groupName: {
            "ar": "الأقسام",
            "ca": "Seccions",
            "zh-CN": "部分",
            "zh-TW": "部分",
            "hr": "Sekcije",
            "cs": "Sekce",
            "da": "Afsnit",
            "nl": "Secties",
            "en": "Sections",
            "fi": "Osat",
            "fr": "Sections",
            "de": "Abschnitte",
            "el": "Ενότητες",
            "he": "מקטעים",
            "hi": "धारा",
            "hu": "Szakaszok",
            "id": "Bagian",
            "it": "Sezioni",
            "ja": "セクション",
            "ko": "섹션",
            "ms": "Bahagian",
            "nb": "Seksjoner",
            "pl": "Sekcje",
            "pt": "Seções",
            "ro": "Secțiuni",
            "ru": "Разделы",
            "sk": "Sekcie",
            "es": "Secciones",
            "sv": "Avsnitt",
            "th": "ส่วนต่างๆ",
            "tr": "Bölümler",
            "uk": "Розділи",
            "vi": "Phần"
          },
        groupId: "sections",
        parentCategoryId: "youPage",
        options: youPageMobileGroups_Sections
    }
]
