CompileFlags:                                          # Tweak the parse settings
Add: [-Wall, -Wextra]                    # treat all files as C++, enable more warnings
    #Add: [-Wall, -Wextra, -std=c++20]                    # treat all files as C++, enable more warnings
    #CompilationDatabasePath: /home/anton/tmp/build
