Player:
Game:
	IntroductionPromptVersion: 1
Sound:
	CashTicks: False
	SoundVolume: 0
	MusicVolume: 0
Graphics:
Server:
	Map: dbc903f08f308a7bd14659a105b2c49632d43168
Debug:
	UUID: 784bfd08-9d21-4ff0-8184-e052e47f78b5
	SendSystemInformation: False
	SystemInformationVersionPrompt: 6
	PerfText: True
	PerfGraph: True
Keys:
